### ISSUE TITLE
naming / terminology changes

### ISSUE THREAD

**Issue by tkellen** [bocoup/skillsbot#11]
#### Do these command names make sense, given that you now tell the bot `<command>` instead of `expertise <command>`?

Current commands names and descriptions:

> **find** - List all team members with the given skill, grouped by interest and experience.
> **for** - List all skills for the given team member, grouped by interest and experience.
> **me** - List all of your skills, grouped by interest and experience.
> **list** - List all skills, grouped by category.
> **scales** - List interest and experience scales.
> **stats** - Provide statistics about a given skill.
> **update** - Update your interest and experience for the given skill.
> **help** - Get help for the specified command.

Old usage (where everything was under the "expertise" sub-command of Robocoup):

> **cowboy**
> expertise for me
> 
> **Robocoup**
> Listing all expertises for @cowboy:
>   ...

New usage (where skillsbot is a totally separate bot that you DM directly):

> **cowboy**
> for me
> 
> **Skills Bot**
> Listing all skills for @cowboy:
>   ...

Command name changes:
- [ ] is the `find` command well named?
  - it might not be obvious that `find` is used to search for users by a given skill, eg `find javascript`, which returns a list of users and their interest/experience levels for that skill.
- [ ] is the `for` command well named?
  - it might not be obvious that `for` is used to search for skills by a given user, eg `for cowboy`, which returns a list of skills and that user's interest/experience levels for each skill.
- [ ] the `me` command is an alias to `for me`. is it well named?
- [ ] is the `list` command well named?
- [ ] is the `scales` command well named?
- [ ] is the `stats` command well named?
- [ ] is the `update` command well named?
- [ ] is the `update missing` sub-command well named?
  - how about `update outstanding`?

General terminology changes:
- [x] any instance of "bocouper" should become "team member"

**Comment by cowboy** [comment]
What about when "bocouper" is referred to in usage, like `expertise for [me | @bocouper]` (#4)?

**Comment by tkellen** [comment]
`[expertise for [me | @teammember]`

**Comment by iamjessklein** [comment]
To address this I propose:
- [ ] usability test the current taxonomy assumptions with 5 - 10 Bocoupers
- [ ] identify if there are any assumptions that need to be refined/tweaked
- [ ] prototype the new/tweaked taxonomy
- [ ] usability test the new taxonomy and tweak
- [ ] document all changes

I think to be safe, we should give this 5 days.

**Comment by cowboy** [comment]
@iamjessklein per your [in-progress wiki document](https://github.com/bocoup/skillsbot/wiki/Command-Naming-Test-Script), I propose an alternative approach:

Instead of asking the test subject to run commands by their name, why not ask them to perform tasks? If we tell them the bot's name is `@skillsbot` and there's a `help` command, their ability to discern the appropriate command names and to perform all of the following tasks could indicate how usable the help information, command names and command functionalities are.
- How are skills categorized?
- How many programming language related skills are there?
- How many people have the maximum possible level of both interest and experience for the "javascript" skill?
- What percentage of people have the maximum possible level of interest for the "work scoping" skill? how about for experience?
- What do the numbers 1-5 for experience and interest mean?
- What skills have you rated at the maximum possible level for both experience and interest?
- Update your experience and interest level for a skill.

(We might want to refine these questions after a run-through)

**Comment by iamjessklein** [comment]
I like this but it only works for a certain kind of user, that is someone who looks for information this way - someone like @brianloveswords or @tkellen might use it for holistic information, but an average engineer or designer is only interested in their own personal skillset and data for the most part. 

This makes me wonder if we need two types of usability scripts - based on the user role.

**Comment by cowboy** [comment]
> This makes me wonder if we need two types of usability scripts - based on the user role.

That sounds like it could be a good idea!

**Comment by tkellen** [comment]
> but an average engineer or designer is only interested in their own personal skillset and data for the most part.

I disagree with this assertion. Discovery of skills for fellow teammates is a very valid use case for everyone, _especially_ new hires.

**Comment by iamjessklein** [comment]
@cowboy and I talked it over and we are going to do guided tasks integrated with feedback questions.  @cowboy explained to me the user stories for the bot and I see that a reason for user skill discovery for engineers or designers could be mentorship (what was I thinking?!) Thanks for calling that out @tkellen 

We have the draft complete at this point and I am ready to begin testing.

**Comment by cowboy** [comment]
This was done in 74b9b9fb5093918dc6a0850042f140e554383669.
